version: "3.9"
services:
  server:
    build: ./flask-backend
    ports:
    - "5000:5000"
    volumes:
    - ./flask-backend:/app
    environment:
      FLASK_ENV: development
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - server